#!/usr/bin/env bash

if [[ -n ${BASH_VERSION+x} ]]; then
    TEST_DIR="${BASH_SOURCE[0]}"
    TEST_DIR=`readlink -f "$TEST_DIR"`
    export TEST_DIR=`dirname "$TEST_DIR"`
elif [[ -n ${ZSH_VERSION+x} ]]; then
    export TEST_DIR=${0:a:h}
fi

TEST_CASES=(
    clear_alias_func_var
    clear_then_load
    restore_on_failure
)

if [[ "$1" == "-v" ]]; then
    export TEST_VERBOSE=1
fi

function run_single_test {
    local test_shell="$1" test_case="$2" ret=0

    echo -n "[$test_shell] $test_case: "
    out_path=`mktemp`
    if ! "$test_shell" "$TEST_DIR/cases/$test_case" >& "$out_path"; then
        echo "FAIL"
        cat "$out_path"
        ret=1
    else
        echo "PASS"
        ret=0
    fi
    rm -f "$out_path"

    return "$ret"
}

for t in ${TEST_CASES[@]}; do
    run_single_test bash "$t" || break
    run_single_test zsh "$t" || break
done
