#!/usr/bin/env bash

# Copyright 2016-2017 Chris Diamand
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [[ -n ${BASH_VERSION+x} ]]; then
    TEST_DIR="${BASH_SOURCE[0]}"
    TEST_DIR=`readlink -f "$TEST_DIR"`
    export TEST_DIR=`dirname "$TEST_DIR"`
elif [[ -n ${ZSH_VERSION+x} ]]; then
    export TEST_DIR=${0:a:h}
fi

TEST_CASES=(
    clear_alias_func_var
    clear_then_load
    override_var
    parent
    reload
    restore_on_failure
    subdir_inherit
)

if [[ "$1" == "-v" ]]; then
    export TEST_VERBOSE=1
    shift
fi

function run_single_test {
    local test_shell="$1" test_case="$2" ret=0

    echo -n "[$test_shell] $test_case: "
    out_path=`mktemp`
    if ! "$test_shell" "$TEST_DIR/cases/$test_case" >& "$out_path"; then
        echo "FAIL"
        cat "$out_path"
        ret=1
    else
        echo "PASS"
        ret=0
    fi
    rm -f "$out_path"

    return "$ret"
}

if [[ $# -gt 0 ]]; then
    TEST_CASES=( "$@" )
fi

for t in ${TEST_CASES[@]}; do
    run_single_test bash "$t" || break
    run_single_test zsh "$t" || break
done
