#!/usr/bin/env bash

if [[ -n ${TEST_VERBOSE+x} ]]; then
    set -o verbose -x
fi

EMGR_DIRS=( "$TEST_DIR/envs" )

function tc_fail() {
    echo "Failed!"
    exit 1
}

function fail_if_var_set() {
    if check_var_set "$1"; then
        echo "Error: '$1' is set, but shouldn't be:" `typeset -p "$1"`
        exit 1
    fi
}

function fail_if_var_not_set() {
    if ! check_var_set "$1"; then
        echo "Error: '$1' is not set, but should be."
        exit 1
    fi
}

function fail_if_function_defined() {
    if type "$1"; then
        echo "Error: '$1' is defined, but shouldn't be:" `type "$1"`
        exit 1
    fi
}

function fail_if_function_not_defined() {
    if ! type "$1" >&/dev/null; then
        echo "Error: '$1' not defined, but it should be."
        exit 1
    fi
}

alias fail_if_alias_defined='fail_if_function_defined'
alias fail_if_alias_not_defined='fail_if_function_not_defined'

function emgr_setup() {
    source "$TEST_DIR/../emgr_setup"
}

function check_var_set() {
    if typeset -p "$1" >&/dev/null; then
        return 0
    else
        return 1
    fi
}
