#!/usr/bin/env bash

# Copyright 2016-2017 Chris Diamand
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


function inherit_env() {
    local env="$1" env_path= old_env_local= err=0
    if [[ -n ${EMGR_ENV_LOCAL+x} ]]; then
        old_env_local="$EMGR_ENV_LOCAL"
    fi

    for e in "${_EMGR_envs_loaded[@]}"; do
        if [[ "$e" == "$env" ]]; then
            echo "Error: Env $env already loaded!"
            return 1
        fi
    done

    env_path=`_EMGR_path_for_env "$env"`

    if [[ -z "$env_path" ]]; then
        echo "Error: Couldn't find env '$env'"
        return 1
    fi

    _EMGR_envs_loaded=( "${_EMGR_envs_loaded[@]}" "$env" )
    export EMGR_ENV_LOCAL="$env"
    source "$env_path" || err=1
    export EMGR_ENV_LOCAL="$old_env_local"
    [[ -n ${EMGR_ENV_LOCAL+x} ]] && unset EMGR_ENV_LOCAL

    return "$err"
}

_EMGR_envs_loaded=()

inherit_env "$EMGR_ENV_CURRENT" && _EMGR_adjust_prompt "$EMGR_ENV_CURRENT"
