#!/usr/bin/env bash

# Copyright 2017 Chris Diamand
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# readlink that works everywhere


if which realpath >&/dev/null; then
    function _EMGR_realpath() {
        realpath "$1"
    }
else
    if which readlink >&/dev/null &&
       [[ -n "`readlink --version 2>&1 grep 'GNU coreutils'`" ]]; then
        function _EMGR_realpath() {
            readlink -m "$1"
        }
    else
        function _EMGR_realpath() {
            if [[ -n "$1" ]]; then
                python -c "import os, sys; print(os.path.realpath(sys.argv[1]))" "$1"
            fi
        }
    fi
fi
