#!/usr/bin/env bash

source $TEST_DIR/test_util

PRESENT_ALL_TIMES=1234

export mypath="/foo:/opt/bar"
myappendarray=(something anotheritem)

emgr_setup

emgr alias_func_list_var

fail_if_var_not_equal mypath "/usr/local/added_by_env:/foo:/opt/bar"

myfunction

X=1

fail_if_var_not_set PRESENT_ALL_TIMES
fail_if_var_not_set TEST1
fail_if_var_not_set X
fail_if_var_not_equal '#myappendarray[@]' 5

emgr --clear

fail_if_var_not_equal mypath "/foo:/opt/bar"
fail_if_var_not_set PRESENT_ALL_TIMES
fail_if_var_set TEST1
fail_if_var_set X

fail_if_function_defined myfunction
fail_if_alias_defined myalias

fail_if_var_not_equal 'myappendarray[*]' "something anotheritem"
fail_if_var_not_equal '#myappendarray[@]' 2

exit 0
