#!/usr/bin/env bash

# Copyright 2016 Chris Diamand
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


source $TEST_DIR/test_util

emgr_setup

PRESENT_ALL_TIMES=1234

alias permanent_alias='ls -lh'

function permanent_func() {
    echo "Function which shouldn't be unset"
}

echo "[1] Loading env"
emgr alias_func_list_var

fail_if_var_not_equal EMGR_ENV_CURRENT "alias_func_list_var"

fail_if_var_not_set TEST1
fail_if_var_not_set PRESENT_ALL_TIMES
fail_if_alias_not_defined permanent_alias
fail_if_function_not_defined permanent_func

echo "[1] Clearing"
emgr --clear

CREATED_AFTER_FIRST_CLEAR=5678

fail_if_var_set TEST1
fail_if_alias_defined myalias
fail_if_function_defined myfunction
fail_if_var_not_set PRESENT_ALL_TIMES
fail_if_var_not_set CREATED_AFTER_FIRST_CLEAR
fail_if_alias_not_defined permanent_alias
fail_if_function_not_defined permanent_func

echo "[2] Loading env"
emgr alias_func_list_var

X=3

fail_if_var_not_set TEST1
fail_if_var_not_set PRESENT_ALL_TIMES
fail_if_var_not_set CREATED_AFTER_FIRST_CLEAR
fail_if_alias_not_defined myalias
fail_if_function_not_defined myfunction
fail_if_alias_not_defined permanent_alias
fail_if_function_not_defined permanent_func

echo "[2] Clearing"
emgr --clear

fail_if_var_set X
fail_if_var_set TEST1
fail_if_alias_defined myalias
fail_if_function_defined myfunction
fail_if_var_not_set PRESENT_ALL_TIMES
fail_if_var_not_set CREATED_AFTER_FIRST_CLEAR
fail_if_alias_not_defined permanent_alias
fail_if_function_not_defined permanent_func

exit 0
