#!/usr/bin/env bash

# Copyright 2016-2017 Chris Diamand
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


source $TEST_DIR/test_util

PRESENT_ALL_TIMES=1234

export mypath="/foo:/opt/bar"
myappendarray=(something anotheritem)

emgr_setup

emgr alias_func_list_var

fail_if_var_not_equal mypath "/usr/local/added_by_env:/foo:/opt/bar"

myfunction

X=1

fail_if_var_not_set PRESENT_ALL_TIMES
fail_if_var_not_set TEST1
fail_if_var_not_set X
fail_if_var_not_equal '#myappendarray[@]' 5

emgr --clear

fail_if_var_not_equal mypath "/foo:/opt/bar"
fail_if_var_not_set PRESENT_ALL_TIMES
fail_if_var_set TEST1
fail_if_var_set X

fail_if_function_defined myfunction
fail_if_alias_defined myalias

fail_if_var_not_equal 'myappendarray[*]' "something anotheritem"
fail_if_var_not_equal '#myappendarray[@]' 2

exit 0
