#!/usr/bin/env bash

source $TEST_DIR/test_util

PRESENT_ALL_TIMES=1234

emgr_setup

emgr alias_func_list_var

myfunction

X=1

fail_if_var_not_set PRESENT_ALL_TIMES
fail_if_var_not_set TEST1
fail_if_var_not_set X

emgr --clear

fail_if_var_not_set PRESENT_ALL_TIMES
fail_if_var_set TEST1
fail_if_var_set X

fail_if_function_defined myfunction
fail_if_alias_defined myalias

exit 0
