#!/usr/bin/env bash

# Copyright 2017-2018 Chris Diamand
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source $TEST_DIR/test_util

emgr_setup

emgr choose_default_value

echo "Default: MYVAR=$MYVAR"
fail_if_var_not_equal MYVAR 3
fail_if_var_not_equal CHOOSE_DEFAULT_RUN 1

emgr --clear

fail_if_var_set MYVAR
fail_if_var_set CHOOSE_DEFAULT_RUN

emgr override_myvar choose_default_value

echo "Overridden: MYVAR=$MYVAR"
fail_if_var_not_equal MYVAR 10
fail_if_var_not_equal CHOOSE_DEFAULT_RUN 1

MYVAR=12345

emgr --reload

fail_if_var_not_equal MYVAR 10
fail_if_var_not_equal CHOOSE_DEFAULT_RUN 1
fail_if_var_not_equal EMGR_ENV_CURRENT "override_myvar+choose_default_value"

! emgr choose_default_value override_myvar
