#!/usr/bin/env bash

# Copyright 2017 Chris Diamand
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


source $TEST_DIR/test_util

emgr_setup

tc_symlink_env reload_env alias_func_list_var

export TEST1="different to env"

echo "[1] Loading env 'reload_env'"
emgr reload_env

fail_if_var_set EMGR_ENV_LOCAL
fail_if_var_not_equal EMGR_ENV_CURRENT "reload_env"
fail_if_var_not_equal TEST1 "hello world!"

export TEST1="again, different to env"

echo "[2] Reloading env 'reload_env'"
emgr --reload

fail_if_var_not_equal TEST1 "hello world!"

echo "[2] Edit env (switch symlink)"
tc_symlink_env reload_env change_test1

emgr --reload

fail_if_var_set EMGR_ENV_LOCAL
fail_if_var_not_equal EMGR_ENV_CURRENT "reload_env"
fail_if_var_not_equal TEST1 "different to alias_func_list_var"
