#!/usr/bin/env bash

source $TEST_DIR/test_util

emgr_setup

tc_symlink_env reload_env alias_func_list_var

export TEST1="different to env"

echo "[1] Loading env 'reload_env'"
emgr reload_env

fail_if_var_not_equal TEST1 "hello world!"

export TEST1="again, different to env"

echo "[2] Reloading env 'reload_env'"
emgr --reload

fail_if_var_not_equal TEST1 "hello world!"

echo "[2] Edit env (switch symlink)"
tc_symlink_env reload_env change_test1

emgr --reload

fail_if_var_not_equal TEST1 "different to alias_func_list_var"
