#!/usr/bin/env bash

# Copyright 2017 Chris Diamand
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


source $TEST_DIR/test_util

emgr_setup

MY_VAR=3141

echo "[1] Load 'fail_load' env"
# This overwrites MY_VAR, but the original value should get restored when
# loading fails.
emgr fail_load

echo "hi"

alias
echo "hi"

fail_if_alias_defined myalias
fail_if_var_not_equal MY_VAR 3141
