fail_if_var_not_equal EMGR_ENV_PARENT subdir/parent2
fail_if_var_not_equal EMGR_ENV_LOCAL subdir2/parent3
fail_if_var_not_equal EMGR_ENV_CURRENT parent1
fail_if_var_not_exported EMGR_ENV_CURRENT
fail_if_var_not_exported EMGR_ENV_LOCAL
fail_if_var_not_exported EMGR_ENV_PARENT
